### ISSUE TITLE
Copta font not loading

### ISSUE THREAD

**Issue by carvalhar** [pjheslin/diogenes#12] opened 2019-05-12 23:38 UTC
![Capture](https://user-images.githubusercontent.com/20246049/57589137-dfad5900-74f5-11e9-9937-5ed1e40e4cc5.PNG)

I saw the CSS is looking for Gentium Plus, but even installed it didn't work.
https://software.sil.org/gentium/download/

**Comment by pjheslin** [comment] 2019-05-13 12:26
There are some issues with Coptic texts, but I cannot reproduce this font problem.  Diogenes comes with Gentium Plus, so you shouldn't have to download it separately.  What Operating System are you using?
![image](https://user-images.githubusercontent.com/9300410/57621160-aa028180-7582-11e9-989c-832da79493a9.png)

**Comment by carvalhar** [comment] 2019-05-13 13:25
Windows 7

**Comment by pjheslin** [comment] 2019-07-15 12:19
I tried this on a Windows 10 machine, and display of Coptic worked fine.

**Comment by pjheslin** [comment] 2019-07-16 20:38
I tried to find a Windows 7 machine to test this, but was not able.  I'll close this issue for now, as it seems to be working on Windows 10.

**Closed by pjheslin** 2019-07-16 20:38 UTC
