### ISSUE TITLE
Could not parse.. any Greek with apostrophe

### ISSUE THREAD

**Issue by helmadik** [pjheslin/diogenes#31] opened 2019-10-04 19:44 UTC
apostrophes also don't carry over to my morphology because I've adopted the modifier letter apostrophe (Unicode 02BC) rather than the simple ' (0027)

**Comment by pjheslin** [comment] 2019-10-05 11:24
The cause of this bug was even more banal than that.  At some point I had added code to clear out any spurious punctuation before looking up the word.  And I stupidly included the apostrophe. It's a fairly long-standing bug, and I managed to convince myself that Morpheus could never handle elided forms, which is not true.

Fixed by commit 044a6cd5fa5cdb14c82be2faece3b11bb3963cdd and will be corrected in version 4.2 when it comes out.  Thanks a million for the report!

**Closed by pjheslin** 2019-10-05 11:24 UTC
