### ISSUE TITLE
Server error in case of long searches

### ISSUE THREAD

**Issue by Doc73** [pjheslin/diogenes#8] opened 2019-04-29 10:57 UTC
Dear Heslin,
I looked for word ἀκηδία in the whole TLG, but the search interrupted itself with the following error:

```
server stderr: [Mon Apr 29 12:53:53 2019] diogenes-server.pl: Diogenes Error: ERROR: Disappearing Match!
```

It is not the first time I notice this issue: it seems in fact the Diogenes can't perform long searches.

Best regards,
DC

**Comment by JayBrown** [comment] 2019-04-29 12:39
It works fine with the Diogenes standalone app.

![snap](https://i.imgur.com/cSAPMzG.jpg)

**Comment by pjheslin** [comment] 2019-04-29 12:41
I was not able to reproduce this.  I did a simple search for ἀκηδία in the TLG, and it completed successfully: 

Passages found: 292

I then tried a TLG word search, looking for all the forms of ἀκηδία in the list, and that also completed successfully:

Incidence of all words as reported by word list: 313
Passages containing those words reported by Diogenes: 292

[Just saw Jay's message.  I wonder why my search produced a different total?]

**Comment by Doc73** [comment] 2019-04-29 12:45
Ah! If I search ἀκηδία with diacritics, Diogenes works, BUT if I search the same word without diacritics ακηδια, it return the above error

**Comment by JayBrown** [comment] 2019-04-29 12:48
@Doc73 : strange, I searched with and without diacritics, and it's always the same result.

@pjheslin : the different passage count is that my results are displayed as paragraph, so when there are two or more instances of a word in one paragraph, it will show as only one result. When I switch to 1 sentence, then I also get 292 results.

**Comment by Doc73** [comment] 2019-04-29 12:55
@pjheslin In my case, Diogenes stops after Eustathius...

![Schermata del 2019-04-29 14-54-37](https://user-images.githubusercontent.com/1306260/56897398-c258a380-6a8e-11e9-9fe0-cb7b3ddac425.png)

**Comment by pjheslin** [comment] 2019-04-29 13:00
I was able to reproduce the error for a search without diacritics: it stops at Eustathius.  I'll look into it.  Thanks for the report!

**Comment by pjheslin** [comment] 2019-04-29 20:28
Commit 2dd9bcafb4c77c5a5424cc85f02456681528a75c should now fix the reported bug.

But Doc was right about there being a general problem with large searches.  As I was debugging the issue above, I found that any search crashes the integrated application when it gets to around 7-800K in size.  This is not a problem with the command-line interface, nor does it happen when you start the server manually and connect to it with the regular Chrome browser.  So there is something going on with the integration with Electron that I will have to look into

**Comment by Doc73** [comment] 2019-04-29 20:34
@pjheslin 
In my case, with Chrome and server started manually, I got the same issue: search stops itself at Eustathius. Boh!

**Comment by pjheslin** [comment] 2019-04-29 20:42
The Eustathius problem had a different cause and should be fixed now.

**Comment by Doc73** [comment] 2019-04-29 20:42
Yes, it is fixed! Thanks!

**Comment by Doc73** [comment] 2019-04-29 20:44
![Schermata del 2019-04-29 22-44-36](https://user-images.githubusercontent.com/1306260/56925716-61ea5600-6ad0-11e9-8543-0235fd16b29e.png)

**Comment by pjheslin** [comment] 2019-04-30 12:53
Commit 61d401561009b61d329b5c10c1011482e1bd73aa now fixes the other problem.  Any search that approached 1MB in output bumped into a buffer limit in Electron, which abruptly killed the server.  That has now been rectified.  (The fix needs testing on Windows, but should be OK).

**Comment by pjheslin** [comment] 2019-04-30 12:54
That should be 6e9739b9c76cfaf9c50336fd1f67ef6018c835e1

**Closed by pjheslin** 2019-04-30 12:53 UTC
