### ISSUE TITLE
File/Download TLL PDFs

### ISSUE THREAD

**Issue by corei8** [pjheslin/diogenes#45] opened 2020-02-07 21:10 UTC
Selecting *Download TLL PDFs* throws this error:

***A JavaScript error occurred in the main process***
```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at click (/Applications/Diogenes.app/Contents/Resources/app/main.js:462:29)
    at MenuItem.click (/Applications/Diogenes.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Diogenes.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

**Comment by pjheslin** [comment] 2020-03-04 20:24
Apologies for the slow response.  I cannot reproduce this error.  Has it persisted, or did it go away?

**Comment by pjheslin** [comment] 2020-04-08 18:40
I'll close this issue for now.  Let me know if it persists.

**Closed by pjheslin** 2020-04-08 18:40 UTC
