### ISSUE TITLE
OLD pdf search for 'oryza'

### ISSUE THREAD

**Issue by mingshey** [pjheslin/diogenes#52] opened 2020-05-09 23:55 UTC
(I thought this constitutes a new issue and brought it up here.)
OLD pdf search for 'atque', 'oscillum', and  'zythos', for example, went smoothly but 'oryza' led to page 1233, the head entry for 'O' instead of its actual position on page 1295.

This was only a small inconvenience but strange still.
I found out that the L-S entry of 'oryza' in lat.ls.perseus-eng1.xml
has 'o^ry_za' as its key and the character 'hat(^)' precedes lowercase
letters in ASCII code table. So if the algorithm uses ASCII based ordering for the search,
'o^ry_za' would be determined to come before 'obaerarius' which is on page 1233.
Based on this assumption my suggestion is to remove all diacritic
characters from the key before searching the entry page in OLD. For example,
$key=~s/[^a-zA-Z0-9]//g
would do the job, I think, if things go simple enough like that.

**Comment by pjheslin** [comment] 2020-05-11 19:41
You were exactly correct about the cause of the bug.  Fixed with commit 5f8fbc5a133f26c45411f944239ead9faca28015.  Thanks for tracking this down!

**Closed by pjheslin** 2020-05-11 19:41 UTC

**Comment by mingshey** [comment] 2020-05-12 16:08
Many thanks for your good work.

**Comment by pjheslin** [comment] 2020-05-12 21:30
It turns out that there was a similar problem with links to the TLL for words with diacritical marks, and these are now fixed, too.

**Comment by mingshey** [comment] 2020-05-13 03:37
Good to know that they're fixed. Thanks for all your work. When is the next build scheduled, I wonder, with recent patches applied?

**Comment by pjheslin** [comment] 2020-05-13 10:01
I have a couple more small bugs on my list to fix (see TODO).  Hopefully I'll fix them and release a new version by the end of the week.

**Comment by pjheslin** [comment] 2020-05-14 19:23
Version 4.5 is out now.

**Comment by mingshey** [comment] 2020-05-15 03:32
Thank you. I'll try it out after today's office hour is over.
