### ISSUE TITLE
v4.0.0 bug: Diogenes makes browser re-download PDFs from localhost

### ISSUE THREAD

**Issue by JayBrown** [pjheslin/diogenes#25] opened 2019-09-24 15:14 UTC
When looking up a word in the dictionary, Diogenes presents the options TLL & OLD in the upper right-hand corner. So far so good.

![snap](https://i.imgur.com/YFbxsDI.jpg)

But when I click on these links (any of the links), it doesn't open the PDF in my default PDF viewer directly (Skim, not Preview), but opens the localhost URL in Firefox, with modified filenames as well, which then asks me whether to open it in Skim, or download it.

![snap](https://i.imgur.com/Jffovl5.jpg)

But it downloads the PDF in any case, from localhost, meaning that it's effectively copying a huge file every time I click on TLL or OLD in Diogenes.

![snap](https://i.imgur.com/p4VqAU0.jpg)

This probably needs to be fixed, because those are unnecessary copy operations that might reduce the SSD lifetime further. (I'm using a RAM disk for all downloads, so it's not an immediate problem on my Mac, but it might be a good thing for other users.)

**Comment by Doc73** [comment] 2019-09-24 15:35
In my PC, with Debian GNU/Linux 10, in both case it opens browser at localhost, but I obtain this result:
**404 Not Found
Location of the requested pdf file has not been set.**

**Comment by JayBrown** [comment] 2019-09-24 16:35
Did you point Diogenes to the TLL and OLD pdf files in the app's "Database Locations" panel?

![snap](https://i.imgur.com/oDFUgiQ.jpg)

**Comment by Doc73** [comment] 2019-09-24 16:41
Ah, ok! Thanks!
But in case of OLD, Diogenes opens a wrong page of the PDF. I did my tests with word _lignum_

**Comment by JayBrown** [comment] 2019-09-24 16:51
You're right: in my case it opens the URL `http://localhost:8888/ox-lat-dict.pdf#page=1051` in my browser, but Skim on macOS only opens page 1.

**Comment by Doc73** [comment] 2019-09-24 16:54
My URl is [http://localhost:8888/ox-lat-dict.pdf#page=1051](http://localhost:8888/ox-lat-dict.pdf#page=1051), but it opens at pag. 1017

I linked a previous my file. Where do you download OLD's pdf????

**Comment by JayBrown** [comment] 2019-09-24 16:56
I downloaded it from genesis.lib (Library Genesis). Might not be the PDF specifically suited for Diogenes. Where did you get yours?

As for the localhost download issue, the PDFs aren't even replaced. Copy after copy.

![snap](https://i.imgur.com/cXGZxSn.jpg)

**Comment by JayBrown** [comment] 2019-09-24 16:58
But it seems to be a problem on macOS, because I just tried it with TLL for "lignum" with URL `http://localhost:8888/tll-pdf/31.pdf#page=22`, but the PDF reader doesn't jump to page 22 either.

**Comment by Doc73** [comment] 2019-09-24 17:02
Under Linux there is only the issue in page numbering: with other latin words, the pdf opens at different pages, even if not correct.

Furthermore, I can't find any `ox-lat-dict.pdf` file in my PC and my original file mantains its name, without changing it.

**Comment by JayBrown** [comment] 2019-09-24 17:05
Diogenes is probably creating a copy of your original file somewhere, either directly or via download (as in my case.) (?)

**Comment by Doc73** [comment] 2019-09-24 17:06
I looked for it both in my home folder and in /tmp folder, but without success

**Comment by pjheslin** [comment] 2019-09-24 20:06
If you have configured your default browser not to open up PDFs itself, but
to download them or pass them off to another application, then then this
functionality will not work.

P.

**Comment by pjheslin** [comment] 2019-09-24 20:07
If it opens to the wrong page, then you have a different PDF from mine.

P.

**Comment by pjheslin** [comment] 2019-09-24 20:09
But you should not be downloading the PDFs.  That is not the intended
usage.

**Comment by pjheslin** [comment] 2019-09-24 20:11
No. That file does not exist. It is part of the URI that serves as a proxy
for the file you point to via the settings.

I’m not understanding what exactly the problem is here.

**Comment by Doc73** [comment] 2019-09-24 20:12
@pjheslin 
Yes, maybe my PDF is different from yours, but my opinion is: is really worth having this so unstable feature, which depends on some specific pdf?

Another question: why in browser is the pdf named `ox-lat-dict.pdf`, although my file has another name?

**Comment by Doc73** [comment] 2019-09-24 20:15
@pjheslin 
I'm sorry, but I read your response at my second question too late. :-D

**Comment by pjheslin** [comment] 2019-09-24 20:19
We’ll see if people like the feature. I have no way of knowing how many
different PDF versions of the OLD are in circulation.

The browser will pull the name ox-lat-dict .pdf out of the URI and will use
it as the file name if you ask the browser to download or save the file.
But why would you do that?

P.

**Comment by Doc73** [comment] 2019-09-24 20:24
@pjheslin 
Yes, I understood! But, please, remember that perhaps it is not always legal to own and/or download that pdf from some site.... :smiley:

**Comment by pjheslin** [comment] 2019-09-24 20:35
I have implemented the OLD functionality for users who own a physical copy of the printed dictionary, as I do, and who have a PDF of it for their personal use.

I'll close this issue now, but I'll make a few points:

- The PDF functionality currently assumes that your default browser is configured to open PDFs directly.  If it isn't, it won't work.  I'll put this in the FAQs.
-  The browsers I have tested will open a PDF to a requested page, but this is an informal spec, so there may be some browsers that don't support it.
- The business of serving the PDFs to a browser via localhost is only necessary because Electron.js does not yet support opening PDFs.  When that functionality is ported from Chrome, it will be possible to open the PDFs directly in the Diogenes application, which will be far more satisfactory.

Peter

**Comment by mlana** [comment] 2019-09-24 22:18
hi peter,
i have a similar problem: when trying to open the TLL from the link up to the right (to go to the word adhuc) the browser shows an URL of the type:
http://localhost:8888/tll-pdf/1.pdf#page=341 (which is right, adhuc is there)
but i get a strange error 404:
Requested pdf file (/Users/mlana/Downloads/ThLL/000924304{ThLL vol. 01 col. 0001â€“0724 (aâ€“adli)}[CC BY-NC-ND].pdf) was not fou
the path is correct but there are those strange characters which probably are the cause of the error. in the Mac, the names of the files in the path are ok. 
any idea?
best
maurizio

**Comment by pjheslin** [comment] 2019-09-25 10:00
This is a separate issue.  I have seen this problem on Windows, but not Macs.  Did you download the PDFs via Diogenes on your Mac or did you download them separately?

P.

**Comment by JayBrown** [comment] 2019-09-25 16:14
I have now set Firefox to always preview PDFs, and it works great. Love this new feature. For other PDFs I'll need to select to download from the contextual menu, but that's fine.

**Comment by pjheslin** [comment] 2019-09-27 10:25
Excellent!  I've added an FAQ about needing to ensure that your default browser is set up to open PDFs.  Thanks for the report.

**Closed by pjheslin** 2019-09-27 10:25 UTC
